language: go

go:
  - "1.13.5"

sudo: required

services:
  - docker

script:
- make dep
- make check
- make test
- make build

deploy:
  provider: script
  script: hack/image_push.sh
  on:
    branch: master
